// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcuewcjncorsiskmtkxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjdWV3Y2puY29yc2lza210a3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODMyMTUsImV4cCI6MjA1OTk1OTIxNX0.4yh5BJ0jWRV2qXcHNnLrqLdc97sLVgQ0s9LpRHurMdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);